name: flurry_navigation
description: A Smooth and Animated navigation package for flutter that doesn’t interfere with the Screen with adjustable colors, shapes, and navigation logic.
version: 0.1.1
author: Youssef Lasheen <ylasheen5@gmail.com>
homepage: https://github.com/YoussefLasheen/flurry_navigation

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    uses-material-design: true
